name: TigerReports
version: ${project.version}
description: Plugin to manage reports / Plugin de gestion de signalements.
author: MrTigreroux
main: fr.mrtigreroux.tigerreports.TigerReports

commands:
  tigerreports:
    description: Informations about TigerReports plugin / Informations sur le plugin TigerReports.
    aliases: [tigerreport]
  report:
    description: Lets report a player / Permet de signaler un joueur.
  reports:
    description: Lets manage reports / Permet de gérer les signalements.
permissions:
  tigerreports.*:
    description: Permet d'accéder a l'ensemble des commandes.
    default: op
    children:
       tigerreports.manage: true
  tigerreports.manage:
    description: Permet de gérer le plugin.
    children:
       tigerreports.advanced: true
       tigerreports.remove: true
       tigerreports.archive: true
  tigerreports.advanced:
    description: Permet de gérer les signalements importants et traités ainsi que les données d'un joueur.
    children:
       tigerreports.staff: true
  tigerreports.remove:
    description: Permet de supprimer un signalement.
    children:
       tigerreports.staff: true
  tigerreports.archive:
    description: Permet d'archiver un signalement.
    children:
       tigerreports.staff: true
  tigerreports.exempt:
    description: Permet d'empecher les autres joueurs de nous signaler.
  tigerreports.teleport:
    description: Permet de se teleporter aux participants d'un signalement.
    children:
       tigerreports.staff: true
  tigerreports.staff:
    description: Permet de gérer les signalements.
    children:
       tigerreports.report: true
  tigerreports.report:
    description: Permet de signaler un joueur.
